### ISSUE TITLE
DataLoader IndexError: Index out of range

### ISSUE THREAD

**Issue by vpapaioannou** [choosehappy/PytorchDigitalPathology#4]
I am loading my data into a pytable according to your code. Then, I am trying to train the U - net using your code as is. I get and IndexError: Index out of range at line

for ii, ( X, y, y_weight) in enumerate( dataLoader[ phase]):

How could I resolve this? When I am using the dataset[ phase] directly it works without any problem so far.

EDIT : I have solved the issue be resolving a bug in creating the pytable database. Previously the database was being created successfully without showing that bug. An indicator of the bug is when the amount of patch images is not the same as the amount of mask/label patch images.

Thanks.

**Comment by vpapaioannou** [comment]
Resolved.

**Comment by choosehappy** [comment]
what was the issue?

**Comment by vpapaioannou** [comment]
The issue was that I wasn't resizing the label image properly. By the way, regarding the test data, I want from the patches to go back to the original image and show the segmentation. How could this be possible given the the way the database is created?

**Comment by choosehappy** [comment]
i would suggest instead using make_output_unet_cmd.py to generate the output directly from the image, instead of trying to stitch together images from the database.

**Comment by vpapaioannou** [comment]
If I understood you correctly, do you mean not to split test image into patches at all? Just feed them as they are? For the moment, I am not using make_output_unet_cmd.py at all. I run the notebooks directly.

**Comment by choosehappy** [comment]
create a validation set and use it with the notebooks

afterwards, use make_output_unet_cmd on the test images

**Comment by vpapaioannou** [comment]
Everything works process wise but, the train/val loss overall increase from epoch to epoch. Is this normal? For epoch 8 train/val loss is ~10% while for epoch 45 it is ~22%.

**Comment by choosehappy** [comment]
hmmmm sorry i'm a bit confused. loss is not measured as a percentage

maybe you can submit a screenshot of the tensorboard graphs?

**Comment by vpapaioannou** [comment]
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:56: RuntimeWarning: invalid value encountered in true_divide

10m 58s (- 1084m 39s) ([1/100] 1%), train loss: 0.1568 val loss: 0.1411  **
21m 51s (- 1070m 22s) ([2/100] 2%), train loss: 0.1559 val loss: 0.1142  **
32m 49s (- 1061m 13s) ([3/100] 3%), train loss: 0.1571 val loss: 0.1209
43m 45s (- 1049m 55s) ([4/100] 4%), train loss: 0.1556 val loss: 0.1267
54m 40s (- 1038m 31s) ([5/100] 5%), train loss: 0.1538 val loss: 0.1213
65m 28s (- 1025m 33s) ([6/100] 6%), train loss: 0.1759 val loss: 0.1241
76m 19s (- 1013m 52s) ([7/100] 7%), train loss: 0.1566 val loss: 0.1834
87m 12s (- 1002m 49s) ([8/100] 8%), train loss: 0.1613 val loss: 0.1303
98m 2s (- 991m 9s) ([9/100] 9%), train loss: 0.1574 val loss: 0.1058  **
108m 52s (- 979m 46s) ([10/100] 10%), train loss: 0.1536 val loss: 0.1255
119m 45s (- 968m 48s) ([11/100] 11%), train loss: 0.1561 val loss: 0.1909
130m 36s (- 957m 43s) ([12/100] 12%), train loss: 0.1583 val loss: 0.1531
141m 37s (- 947m 41s) ([13/100] 13%), train loss: 0.1747 val loss: 0.1346
152m 37s (- 937m 31s) ([14/100] 14%), train loss: 0.1573 val loss: 0.1411
163m 40s (- 927m 23s) ([15/100] 15%), train loss: 0.1566 val loss: 0.1072
174m 36s (- 916m 37s) ([16/100] 16%), train loss: 0.1533 val loss: 0.1298
185m 36s (- 906m 8s) ([17/100] 17%), train loss: 0.1629 val loss: 0.1309
196m 37s (- 895m 41s) ([18/100] 18%), train loss: 0.1538 val loss: 0.2265
207m 41s (- 885m 20s) ([19/100] 19%), train loss: 0.1825 val loss: 0.3491
218m 40s (- 874m 38s) ([20/100] 20%), train loss: 0.2210 val loss: 0.2223
229m 37s (- 863m 44s) ([21/100] 21%), train loss: 0.2222 val loss: 0.2355
240m 39s (- 853m 12s) ([22/100] 22%), train loss: 0.2269 val loss: 0.2409
251m 36s (- 842m 17s) ([23/100] 23%), train loss: 0.2261 val loss: 0.2235
262m 35s (- 831m 29s) ([24/100] 24%), train loss: 0.2274 val loss: 0.2328
273m 33s (- 820m 37s) ([25/100] 25%), train loss: 0.2275 val loss: 0.2466
284m 36s (- 810m 1s) ([26/100] 26%), train loss: 0.2271 val loss: 0.2268
295m 34s (- 799m 5s) ([27/100] 27%), train loss: 0.2272 val loss: 0.2499
306m 37s (- 788m 26s) ([28/100] 28%), train loss: 0.2271 val loss: 0.2249
317m 41s (- 777m 45s) ([29/100] 28%), train loss: 0.2259 val loss: 0.2219
328m 44s (- 767m 1s) ([30/100] 30%), train loss: 0.2270 val loss: 0.2323
339m 45s (- 756m 11s) ([31/100] 31%), train loss: 0.2274 val loss: 0.2354
350m 43s (- 745m 14s) ([32/100] 32%), train loss: 0.2279 val loss: 0.2225
361m 39s (- 734m 14s) ([33/100] 33%), train loss: 0.2261 val loss: 0.2285
372m 38s (- 723m 20s) ([34/100] 34%), train loss: 0.2265 val loss: 0.2232
383m 43s (- 712m 36s) ([35/100] 35%), train loss: 0.2265 val loss: 0.2221
394m 45s (- 701m 46s) ([36/100] 36%), train loss: 0.2258 val loss: 0.2225
405m 41s (- 690m 44s) ([37/100] 37%), train loss: 0.2273 val loss: 0.2240
416m 36s (- 679m 42s) ([38/100] 38%), train loss: 0.2270 val loss: 0.2269
427m 36s (- 668m 47s) ([39/100] 39%), train loss: 0.2259 val loss: 0.2240
438m 39s (- 657m 58s) ([40/100] 40%), train loss: 0.2252 val loss: 0.2280
449m 39s (- 647m 3s) ([41/100] 41%), train loss: 0.2256 val loss: 0.2262
460m 41s (- 636m 10s) ([42/100] 42%), train loss: 0.2262 val loss: 0.2227
471m 44s (- 625m 18s) ([43/100] 43%), train loss: 0.2266 val loss: 0.2237
482m 52s (- 614m 32s) ([44/100] 44%), train loss: 0.2270 val loss: 0.2317
494m 0s (- 603m 45s) ([45/100] 45%), train loss: 0.2271 val loss: 0.2260

By the way, the graphs don't work, at least they are not shown.

Thanks.

**Comment by choosehappy** [comment]
yup, this is incorrect. at bare minimum loss should always be decreasing on the training set

graphs need to be viewed in tensorboard, they won't appear in the jupyter notebook

**Comment by vpapaioannou** [comment]
How could I fix this then? I am thinking of using an lr_scheduler or something similar.

**Comment by choosehappy** [comment]
hard to give advice as i don't know what you're doing. the code + data
work as is, without any modifications

if you've changed the data, network, etc, there are a number of days forward

in this case, adding a lr scheduler will not help. if the training loss is
increasing, something is likely fundamentally wrong with the setup, ADAM is
designed to avoid having any such hyper parameters

https://towardsdatascience.com/learning-rate-schedules-and-adaptive-learning-rate-methods-for-deep-learning-2c8f433990d1

**Comment by vpapaioannou** [comment]
Thanks, the only change that I made compared to the original code is that when I load the training data, at the same time I load the mask/label data to make sure that there is correspondence between the two. I could send/upload the notebooks if it would help.

**Comment by choosehappy** [comment]
try using the original code, as is, first. see if it works. a number of
people have copy->pasted it without an issue, so if it doesn't work, then
there may be some library/version issues which need to be addressed
