### ISSUE TITLE
TypeError: self.dims,self.dims_chunk,self.maxdims cannot be converted to a Python object for pickling

### ISSUE THREAD

**Issue by lunasdejavu** [choosehappy/PytorchDigitalPathology#5]
I used the project  on your website from [here](https://github.com/choosehappy/PytorchDigitalPathology/tree/master/segmentation_epistroma_unet)  and nuclei dataset on your dataset from [here](http://andrewjanowczyk.com/wp-static/nuclei.tgz)
after I made the pytable file by make_hdf5.py
```
patch_size=500 #size of the tiles to extract and save in the database, must be >= to training size
stride_size=250 #distance to skip between patches, 1 indicated pixel wise extraction, patch_size would result in non-overlapping tiles
mirror_pad_size=250 # number of pixels to pad *after* resize to image with by mirroring (edge's of patches tend not to be analyzed well, so padding allows them to appear more centered in the patch)
test_set_size=.1 # what percentage of the dataset should be used as a held out validation/testing set
resize=1 #resize input images
classes=[0,1] #
```
I train by  [train_unet.ipnb](https://github.com/choosehappy/PytorchDigitalPathology/blob/master/segmentation_epistroma_unet/train_unet.ipynb)

but the error showed up
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-a5149657a6ab> in <module>
     16             model.eval()   # Set model to evaluate mode
     17 
---> 18         for ii , (X, y, y_weight) in enumerate(dataLoader[phase]): #for each of the batches
     19             X = X.to(device)  # [Nbatch, 3, H, W]
     20             y_weight = y_weight.type('torch.FloatTensor').to(device)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
    191 
    192     def __iter__(self):
--> 193         return _DataLoaderIter(self)
    194 
    195     def __len__(self):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
    467                 #     before it starts, and __del__ tries to join but will get:
    468                 #     AssertionError: can only join a started process.
--> 469                 w.start()
    470                 self.index_queues.append(index_queue)
    471                 self.workers.append(w)

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     87             try:
     88                 reduction.dump(prep_data, to_child)
---> 89                 reduction.dump(process_obj, to_child)
     90             finally:
     91                 set_spawning_popen(None)

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tables\hdf5extension.cp37-win_amd64.pyd in tables.hdf5extension.Array.__reduce_cython__()

TypeError: self.dims,self.dims_chunk,self.maxdims cannot be converted to a Python object for pickling
```
what mistake did I make?

**Comment by choosehappy** [comment]
it looks like you're using windows. what happens if you set num_workers = 0?

pytorch has always had issues in windows with forking and jupyter notebooks

if you want # of workers to be higher, you can export the notebook as python code and it should work ok from the command line (might need a small modification: https://github.com/choosehappy/PytorchDigitalPathology/issues/5)

**Comment by lunasdejavu** [comment]
@choosehappy  thanks I found there was a discussion about how many workers should we choose,
one person said it should be 2* numbers of GPU. And I think it works since the time between different epochs is much smaller.
btw can I asked one more stupid question?
my pth is [here](https://drive.google.com/file/d/1USezYuBIjUQ_vI_JC0NSCGWjebkXlxab/view?usp=sharing)
I encountered another error  in make_output_unet_cmd.py
```
Traceback (most recent call last):
  File "make_output_unet_cmd.py", line 57, in <module>
    model.load_state_dict(checkpoint["model_dict"])
  File "/home/willysung/.conda/envs/envwilly/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for UNet:
        Missing key(s) in state_dict: "down_path.0.block.0.weight", "down_path.0.block.0.bias", "down_path.0.block.2.weight", "down_path.0.block.2.bias", "down_path.0.block.2.running_mean", "down_path.0.block.2.running_var", "down_path.0.block.3.weight", "down_path.0.block.3.bias", "down_path.0.block.5.weight", "down_path.0.block.5.bias", "down_path.0.block.5.running_mean", "down_path.0.block.5.running_var", "down_path.1.block.0.weight", "down_path.1.block.0.bias", "down_path.1.block.2.weight", "down_path.1.block.2.bias", "down_path.1.block.2.running_mean", "down_path.1.block.2.running_var", "down_path.1.block.3.weight", "down_path.1.block.3.bias", ...
```
I don't know why the function can't catch any parameters ...

**Comment by choosehappy** [comment]
something weird has gone on here...

this is your file:

![image](https://user-images.githubusercontent.com/9681868/58309278-1774a480-7e04-11e9-8bb7-0f87387e4e8a.png)


and this is my file:

![image](https://user-images.githubusercontent.com/9681868/58309290-1e9bb280-7e04-11e9-86e3-b609844edd37.png)


note that all of your paramters start with 

module.down_path.0.block.0.weight

and mine are like this:

down_path.0.block.0.weight

which is what the U-Net is expecting

how did you make this checkpoint?

**Comment by lunasdejavu** [comment]
ah I fixed by `model.load_state_dict(torch.load(PATH), strict=False)?` since I used multi GPU
but then I found that the output are all zeros...
I tested with the training image it is still the same.
what mistake could it be?

**Comment by choosehappy** [comment]
Did you try using a single GPU? Many people have used this code without issue, so i'm wondering if there are some other changes you've made or if you're using a unique/different environment?

**Comment by lunasdejavu** [comment]
my code is [here](https://drive.google.com/file/d/10Kj2fHQD88PLeJKRgDW0nIlbo3aNXs2_/view?usp=sharing)
I followed some tutorials and  changed this:
```
gpu_ids = [2, 3]
#specify if we should use a GPU (cuda) or only the CPU
#print(torch.cuda.get_device_properties(gpuid))
#torch.cuda.set_device(gpuid)
#device = torch.device(f'cuda:{gpuid}' if torch.cuda.is_available() else 'cpu')
device = torch.device('cuda:{}'.format(gpu_ids[0]) if torch.cuda.is_available() else 'cpu')
```
and
```
model = UNet(n_classes=n_classes, in_channels=in_channels, padding=padding,depth=depth,wf=wf, up_mode=up_mode, batch_norm=batch_norm).to(device)
print(f"total params: \t{sum([np.prod(p.size()) for p in model.parameters()])}")
model = nn.DataParallel(model,device_ids=[2, 3])
```

**Comment by choosehappy** [comment]
ah. i don't know of if this unet code was designed to work unmodified with
multiple GPUs

can you try using a single one?

**Comment by lunasdejavu** [comment]
sure but since I read the training loss and validation loss, I think your code still works fine, but it might change a little for output

**Comment by choosehappy** [comment]
see here:

https://discuss.pytorch.org/t/prefix-parameter-names-in-saved-model-if-trained-by-multi-gpu/494

**Comment by lunasdejavu** [comment]
there is another kind of error jumped out:
```
  File "make_output_unet_cmd.py", line 62, in <dictcomp>
    state_dict = {k.partition('model.')[2]: v for k,v in state_dict}
ValueError: too many values to unpack (expected 2)
```
it is so weird

**Comment by lunasdejavu** [comment]
the event file
https://drive.google.com/file/d/1n3Vj6jrcwwAVaHcZS19qCud6bS6SZdFN/view?usp=sharing
finally, I got the result 
https://imgur.com/8Cv15I3
my batchsize is 256 
the mask from the model I trained is quite different from the ground truth.
the training loss decreased smoothly　but the validation loss didn't.
TP didn't increase much.
Can you give me some suggestion ? first time to do the medical  problem...

**Comment by lunasdejavu** [comment]
I think the problem is the nuclei dataset your provided 
https://imgur.com/QjghRop
the central mask is the ground truth and the right one is from Unet.
I am not an expert but  it seems that the author of the dataset didn't segment all the nuclei on the image according to the original image.

**Comment by choosehappy** [comment]
correct, you can read more about it here:

http://www.andrewjanowczyk.com/use-case-1-nuclei-segmentation/

and in the original paper:

http://www.jpathinformatics.org/article.asp?issn=2153-3539;year=2016;volume=7;issue=1;spage=29;epage=29;aulast=Janowczyk;type=3
