### ISSUE TITLE
make_output_unet_cmd.py excution

### ISSUE THREAD

**Issue by mbmhm123** [choosehappy/PytorchDigitalPathology#7]
i use this
ipdb> make_output_unet_cmd.py imgBF.tif --model  epistroma_unet_best_model,pth
ipdb> make_output_unet_cmd.py *.tif --model  epistroma_unet_best_model,pth

but it make error.

invaild syntax. how i can solve this.

tif file and pth file exist at same file

i use window

**Comment by choosehappy** [comment]
is that a comma instead of a period in your model name?

**Comment by mbmhm123** [comment]
yes. i used comma. Sorry. i misspelled it

**Comment by mbmhm123** [comment]
make_output_unet_cmd.py *.tif --model epistroma_unet_best_model.pth
  File "<ipython-input-8-ad325fe678dc>", line 1
    make_output_unet_cmd.py *.tif --model epistroma_unet_best_model.pth
                             ^
SyntaxError: invalid syntax

**Comment by choosehappy** [comment]
what happens when you run it directly from the command line without any parameters, does it look like this?


![image](https://user-images.githubusercontent.com/9681868/62535928-f2150580-b84c-11e9-9784-075b3173bf77.png)

**Comment by mbmhm123** [comment]
>in[1]: make_output_unet_cmd.py
Traceback (most recent call last):

  File "<ipython-input-1-54b64a704462>", line 1, in <module>
    make_output_unet_cmd.py

NameError: name 'make_output_unet_cmd' is not defined


or i press F5 key.

runfile('C:/Users/mbmhm/Desktop/unet/make_output_unet_cmd.py', wdir='C:/Users/mbmhm/Desktop/unet')
usage: make_output_unet_cmd.py [-h] [-p PATCHSIZE] [-s BATCHSIZE] [-o OUTDIR]
                               [-r RESIZE] [-m MODEL] [-i GPUID] [-f]
                               [-b BASEPATH]
                               [input_pattern [input_pattern ...]]
make_output_unet_cmd.py: error: No images selected with input pattern
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

C:\Users\mbmhm\ansel\Anaconda3\envs\moongpu\lib\site-packages\IPython\core\interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by choosehappy** [comment]
if you plan to run the script from the command line, you'll need to do
something like this:
https://www.cs.bu.edu/courses/cs108/guides/runpython.html   as the python
script cannot be run "by itself" and needs an interpreter (first error)


for your particular development tools (second error), this seems to be done
for you but you'll need to consult their documentation about how to execute
scripts and provide parameters to it
